proyectoCaritas/HopeTrade/hopetrade/urls.py
from django.contrib import admin
from django.urls import path, include
from sesiones import views as sesiones

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sesiones/', include(('sesiones.urls', 'sesiones'))),
    path('publicaciones/', include(('publicaciones.urls', 'publicaciones'))),
    path('intercambios/', include(('intercambios.urls', 'intercambios'))),
    path('listados/', include(('listados.urls', 'listados'))),
    path('', sesiones.ver_landing_page),
    path('ofrecimientos/', include('ofrecimientos.urls')),
    path('historiales/', include(('historiales.urls', 'historiales'))),
    path('estadisticas/', include(('estadisticas.urls', 'estadisticas'))),
    path('donaciones/', include(('donaciones.urls', 'donaciones')))
]

proyectoCaritas/HopeTrade/listados/urls.py
from django.urls import path
from . import views
from intercambios import views as intercambios_views

urlpatterns = [
    path('agregar_categoria/', views.agregar_categoria, name='agregar_categoria'),
    path('listar_categorias/', views.listar_categorias, name='listar_categorias'),
    path('editar_categoria/<int:categoria_id>/', views.editar_categoria, name='editar_categoria'),
    path('eliminar_categoria/<int:categoria_id>/', views.eliminar_categoria, name='eliminar_categoria'),
    path('listar_intercambios_del_dia/', views.list_exchanges_today, name='listar_intercambios_del_dia'),
    path('listar_intercambios_del_dia/confirmar/<int:intercambio_id>/', intercambios_views.confirm_exchange, name='listar_intercambios_del_dia_confirmar'),
]

proyectoCaritas/HopeTrade/ofrecimientos/urls.py
from django.urls import path
from . import views

app_name = 'ofrecimientos'

urlpatterns = [
    path('publicaciones/realizar_ofrecimiento/', views.realizar_ofrecimiento),
    path('seleccionar_publicacion/<int:publicacion_id>/realizar_ofrecimiento/', views.realizar_ofrecimiento, name='realizar_ofrecimiento'),
    path('ver_ofrecimientos/<int:publicacion_id>', views.ver_ofrecimientos, name='ver_ofrecimientos'),
    path('aceptar_ofrecimiento/<int:ofrecimiento_id>', views.aceptar_ofrecimiento, name='aceptar_ofrecimiento'),
    path('rechazar_ofrecimiento/<int:ofrecimiento_id>', views.rechazar_ofrecimiento, name='rechazar_ofrecimiento'),
    path('ver_mis_ofrecimientos/<int:user_id>', views.ver_mis_ofrecimientos, name='ver_mis_ofrecimientos'),
    path('eliminar_ofrecimientos/<int:ofrecimiento_id>', views.eliminar_ofrecimiento, name='eliminar_ofrecimiento'),
    path('cancelar_operacion/<int:publicacion_id>', views.cancelar_operacion, name='cancelar_operacion'),

]

proyectoCaritas/HopeTrade/ofrecimientos/models.py
from django.db import models
from listados.models import Categoria
from sesiones.models import Usuario
from publicaciones.models import Publicacion

# Create your models here.
class Sucursal(models.Model):
    nombre = models.TextField()
    ubicacion = models.CharField(max_length=100)

class Ofrecimiento(models.Model):
    fecha = models.DateTimeField()
    articulo = models.CharField(max_length=100)
    cantidad = models.IntegerField()
    descripcion = models.CharField(max_length=250)
    estado = models.TextField()
    imagen = models.BinaryField(null=True, blank=True, editable=True)
    usuarioId = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    categoriaId = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    sucursalId = models.ForeignKey(Sucursal, on_delete=models.CASCADE)
    publicacionId = models.ForeignKey(Publicacion, on_delete=models.CASCADE)

proyectoCaritas/HopeTrade/ofrecimientos/forms.py
from django import forms
from .models import Ofrecimiento
from .models import Sucursal
from listados.models import Categoria
from django.utils import timezone

class RealizarOfrecimiento(forms.ModelForm):
    class Meta:
        model = Ofrecimiento
        fields = ('fecha','articulo', 'cantidad', 'descripcion', 'imagen', 'categoriaId', 'sucursalId')
    
    cantidad = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    fecha = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={'placeholder': 'dd/mm/aaaa HH:MM', 'class': 'form-control'}),
        input_formats=['%d/%m/%Y %H:%M']
    )
    categoriaId = forms.ModelChoiceField(
        queryset=Categoria.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    sucursalId = forms.ModelChoiceField(
        queryset=Sucursal.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    descripcion = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    imagen = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super(RealizarOfrecimiento, self).__init__(*args, **kwargs)
        self.fields['categoriaId'].label_from_instance = lambda obj: "%s" % obj.titulo
        self.fields['sucursalId'].label_from_instance = lambda obj: "%s" % obj.nombre

    def clean_fecha(self):
        fecha = self.cleaned_data.get('fecha')
        # Verificar si la fecha es posterior al día actual
        if fecha <= timezone.now():
            raise forms.ValidationError("Ingrese una fecha válida.")
        # Verificar si la fecha está entre lunes y viernes
        if fecha.weekday() > 4:  # 0 = lunes, 4 = viernes
            raise forms.ValidationError("Ingresar un día entre lunes y viernes.")
        # Verificar si la hora está entre 8:00 y 20:00
        if fecha.hour < 8 or fecha.hour >= 20:
            raise forms.ValidationError("Ingresar un horario entre las 08:00 y las 20:00.")
        return fecha
    
class escribir_texto_cancelacion(forms.Form):
    texto = forms.CharField(
        required=False,
        empty_value='',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'ej: sucursal muy lejana'
        }),
        label='Razón'
    )

proyectoCaritas/HopeTrade/ofrecimientos/views.py
from django.shortcuts import render, redirect, reverse
from sesiones.models import Usuario
from publicaciones.models import Publicacion, Categoria
from intercambios.models import Intercambio
from .models import Ofrecimiento
from .forms import RealizarOfrecimiento, escribir_texto_cancelacion
from intercambios.forms import realizarIntercambio
from sesiones.views import enviar_mail
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from datetime import datetime
import base64
from historiales.models import Historial, PublicacionHistorial, IntercambioHistorial

# Create your views here.
def realizar_ofrecimiento(request, publicacion_id):
    if request.method == "POST":
        realizar_ofrecimiento_form = RealizarOfrecimiento(request.POST, request.FILES)
        if realizar_ofrecimiento_form.is_valid():
            try:
                ofrecimiento = realizar_ofrecimiento_form.save(commit=False)
                usuarioId = request.session.get('rol_id')
                ofrecimiento.usuarioId = Usuario.objects.get(id=usuarioId)
                ofrecimiento.publicacionId = Publicacion.objects.get(id=publicacion_id)
                imagen=(
                    base64.b64encode(realizar_ofrecimiento_form.cleaned_data["imagen"].read())
                    if realizar_ofrecimiento_form.cleaned_data["imagen"]
                    else realizar_ofrecimiento_form.cleaned_data["imagen"]
                )
                ofrecimiento.imagen = imagen
                ofrecimiento.estado = 'pendiente'
                ofrecimiento.save()
                subject = f"¡Hola!, te han realizado un ofrecimiento para la publicacion del producto {ofrecimiento.publicacionId.titulo}, saludos!"
                enviar_mail("Tu publicacion de Hope Trade", subject, ofrecimiento.publicacionId.usuarioId.email, ofrecimiento.publicacionId.usuarioId.personaId.nombre)
                messages.success(request, "El ofrecimiento se creó exitosamente")
                ruta = "/publicaciones/seleccionar_publicacion/" + str(publicacion_id)
                return redirect(ruta)
            except:
                return render(request, "ofrecimientos/realizar_ofrecimiento.html", {
                    'form': RealizarOfrecimiento(),
                    "error": 'algo salió mal'
                })
    else:
        realizar_ofrecimiento_form = RealizarOfrecimiento()
    return render(request, "ofrecimientos/realizar_ofrecimiento.html", {
        'realizar_ofrecimiento_form': realizar_ofrecimiento_form
    })

def ver_ofrecimientos(request, publicacion_id):
    publicacion = Publicacion.objects.get(id=publicacion_id)
    ofrecimientosPublicacion = Ofrecimiento.objects.all().filter(publicacionId=publicacion).exclude(estado='eliminado')
    categorias = Categoria.objects.all()
    ofrecimiento_info = []
    for ofrecimiento in ofrecimientosPublicacion:
        aux = {
            "id": ofrecimiento.id,
            "articulo": ofrecimiento.articulo,
            "cantidad": ofrecimiento.cantidad,
            "fecha": ofrecimiento.fecha,
            "descripcion": ofrecimiento.descripcion,
            "imagen": None,
            "sucursalId":ofrecimiento.sucursalId,
            "usuarioId":ofrecimiento.usuarioId,
        }
        if ofrecimiento.imagen:
            imagen = ofrecimiento.imagen.decode("utf-8")
            aux["imagen"] = imagen
        ofrecimiento_info.append(aux)
    if len(ofrecimientosPublicacion) == 0:
        messages.warning(request, 'Esta publicación no tiene ofrecimientos')
    return render(request, "ofrecimientos/ver_ofrecimientos.html", {
        'ofrecimientosPublicacion': ofrecimiento_info,
        'categorias': categorias,
    })

def aceptar_ofrecimiento(request, ofrecimiento_id):
    ofrecimiento = Ofrecimiento.objects.get(id=ofrecimiento_id)

    if request.method == 'POST':    
        datos = {
            'estado': 'pendiente',
            'valoracion1': False,
            'valoracion2': False,
            'ofrecimientoId': ofrecimiento.id
        }
        realizar_intercambio_form = realizarIntercambio(data=datos)
    
        if realizar_intercambio_form.is_valid():
            intercambio = realizar_intercambio_form.save(commit=False)
            intercambio.save()
            #SE CREA UN LOG EN EL HISTORIAL DE INTERCAMBIOS
            historial = Historial.objects.create(estado="pendiente", fecha=datetime.now())
            IntercambioHistorial.objects.create(intercambioId=intercambio, historialId=historial)
            
            publicacion = Publicacion.objects.get(id=ofrecimiento.publicacionId.id)
            publicacion.estado = 'aceptada'
            publicacion.save()
            #SE CREA UN LOG EN EL HISTORIAL
            historial = Historial.objects.create(estado="aceptada", fecha=datetime.now())
            PublicacionHistorial.objects.create(publicacionId=publicacion, historialId=historial)
    
            subject = f"¡Hola!, tu ofrecimiento para la publicacion del producto {publicacion.titulo}, a nombre de {publicacion.usuarioId.personaId.nombre} fue aceptado, te esperamos!"
            enviar_mail("Tu ofrecimiento de Hope Trade", subject, ofrecimiento.usuarioId.email, ofrecimiento.usuarioId.personaId.nombre)
            ofrecimiento.estado = 'aceptado'
            ofrecimiento.save()
            messages.success(request, "El ofrecimiento se aceptó exitosamente")
            return redirect( "/publicaciones/listar_publicaciones_sistema/")
        else:
            print('Formulario no válido. Errores:')
            for field, errors in realizar_intercambio_form.errors.items():
                for error in errors:
                    print(f"Error en {field}: {error}")
    return render(request, 'ofrecimientos/aceptar_ofrecimiento.html',{
        'ofrecimiento': ofrecimiento
    })

def rechazar_ofrecimiento(request, ofrecimiento_id):
    ofrecimiento = Ofrecimiento.objects.get(id=ofrecimiento_id)
    publicacion = Publicacion.objects.get(id=ofrecimiento.publicacionId.id)
    if request.method == 'POST':
        form = escribir_texto_cancelacion(request.POST)
        if form.is_valid():
            texto = form.cleaned_data['texto']
            if not texto.strip():
                subject = f"¡Hola!, tu ofrecimiento para la publicacion del producto {publicacion.titulo}, a nombre de {publicacion.usuarioId.personaId.nombre} fue rechazado."
            else:
                subject = f"¡Hola!, tu ofrecimiento para la publicacion del producto {publicacion.titulo}, a nombre de {publicacion.usuarioId.personaId.nombre} fue rechazado. La razón: {texto}"
            enviar_mail("Tu ofrecimiento de Hope Trade", subject, ofrecimiento.usuarioId.email, ofrecimiento.usuarioId.personaId.nombre)
            ofrecimiento.estado = 'eliminado'
            ofrecimiento.save()
            messages.success(request, "El ofrecimiento se rechazó exitosamente")
            url = reverse('ofrecimientos:ver_ofrecimientos', kwargs={'publicacion_id': publicacion.id})
            return redirect(url)
    else:
        form = escribir_texto_cancelacion()
    return render(request, 'ofrecimientos/rechazar_ofrecimiento.html',{
        'form': form ,
        'publicacionId': publicacion.id,
    })

def cancelar_operacion(request, publicacion_id):
    ruta = "/ofrecimientos/ver_ofrecimientos/" + str(publicacion_id)
    return redirect(ruta)


























############################################################################################################
def ver_mis_ofrecimientos(request, user_id):
    try:
        usuario = Usuario.objects.get(id=user_id)
        ofrecimientos = Ofrecimiento.objects.filter(usuarioId=usuario).exclude(estado='eliminado').exclude(estado='aceptado')
    except ObjectDoesNotExist:
        messages.warning(request, 'No tienes ningún ofrecimiento activo')
    if len(ofrecimientos) == 0:
        messages.warning(request, "No tienes ningún ofrecimiento activo")
    ofrecimientos_final = []
    for ofrecimiento in ofrecimientos:
        ofrecimiento_con_imagen = {
            "id": ofrecimiento.id,
            "articulo": ofrecimiento.articulo,
            "cantidad": ofrecimiento.cantidad,
            'fecha': ofrecimiento.fecha,
            "descripcion": ofrecimiento.descripcion,
            'publicacionId': ofrecimiento.publicacionId,
            "imagen": None,
            "sucursalId":ofrecimiento.sucursalId,
        }
        if ofrecimiento.imagen:
            imagen = ofrecimiento.imagen.decode("utf-8")
            ofrecimiento_con_imagen["imagen"] = imagen
        ofrecimientos_final.append(ofrecimiento_con_imagen)
    return render(request, 'ofrecimientos/ver_mis_ofrecimientos.html', {
        'ofrecimientos': ofrecimientos_final,
    })
    
def eliminar_ofrecimiento(request, ofrecimiento_id):
    ofrecimiento = Ofrecimiento.objects.get(id=ofrecimiento_id)
    if request.method == "POST":
        ofrecimiento.estado = 'eliminado'
        ofrecimiento.save()
        messages.success(request, "El ofrecimiento se eliminó exitosamente")
        return redirect('ofrecimientos:ver_mis_ofrecimientos', user_id=request.session['rol_id'])
    ofrecimiento.imagen = ofrecimiento.imagen.decode("utf-8")
    return render(request, 'ofrecimientos/eliminar_ofrecimiento.html', { 'ofrecimiento': ofrecimiento })
############################################################################################################
    


proyectoCaritas/HopeTrade/templates/ofrecimientos/aceptar_ofrecimiento.html
{% extends 'base.html' %}

{% block title %}
        <title>Aceptar Ofrecimiento</title>
{% endblock title %}

{% block content %}
        
<form method="POST">
<div class="container mt-5">
        <div class="row justify-content-center">
                <div class="col-md-6 text-center">
                        {% csrf_token %}
                        <div class="card">
                                <div class="card-body">
                                        <h1 class="mb-4"> ¿Estás seguro que deseas aceptar el ofrecimiento?</h1>

                                        <button type="submit" class="btn btn-success">
                                                Aceptar
                                        </button>
                                        
                                        <a href="{% url 'ofrecimientos:cancelar_operacion' ofrecimiento.publicacionId.id %}" class="btn btn-danger">Cancelar</a>
                                </div>
                        </div>
                </div>
        </div>
</div>
</form>

{% endblock content %}

proyectoCaritas/HopeTrade/templates/ofrecimientos/realizar_ofrecimiento.html
{% extends 'base.html' %}

{% block title %}
        <title>Ofrecimiento</title>
{% endblock title %}
{% block content %}

    <form method="POST" enctype="multipart/form-data" class="custom-form">
    
        {% csrf_token %}

        <div class="col-md-5 mx-auto">
            <div class="card p-4">
                <h1 style="font-size: 2em;">Nuevo Ofrecimiento<h1></h1>
                <div class="mb-3">
                    <label class="form-label" style="font-size: 20px;">Fecha</label>
                    <input type="datetime-local" id="id_fecha" name="fecha" class="form-control {% if realizar_ofrecimiento_form.fecha.errors %}is-invalid{% endif %}" placeholder="dd/mm/aaaa HH:MM" name="fecha" value="{{ request.POST.fecha }}"">
                    {% for error in realizar_ofrecimiento_form.fecha.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                </div>
                <div class="mb-3">
                    <label class="form-label" style="font-size: 20px;">Articulo</label>
                    <input type="text" class="form-control {% if realizar_ofrecimiento_form.titulo.errors %}is-invalid{% endif %}" placeholder="articulo" name="articulo" value="{{ request.POST.articulo }}">
                    {% for error in realizar_ofrecimiento_form.articulo.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                </div>
                <div class="mb-3">
                    <label class="form-label" style="font-size: 20px;">Cantidad</label>
                    <input type="text" class="form-control {% if realizar_ofrecimiento_form.cantidad.errors %}is-invalid{% endif %}" placeholder="cantidad" name="cantidad" value="{{ request.POST.cantidad }}">
                    {% for error in realizar_ofrecimiento_form.cantidad.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                </div>
                <div class="mb-3">
                    <label class="form-label" style="font-size: 20px;">Descripcion</label>
                    <input type="text" class="form-control {% if realizar_ofrecimiento_form.descripcion.errors %}is-invalid{% endif %}" placeholder="descripcion" name="descripcion" value="{{ request.POST.descripcion }}">
                    {% for error in realizar_ofrecimiento_form.descripcion.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                </div>
                <div class="mb-3">
                    <label class="form-label" style="font-size: 20px;">Imagen</label>
                    <input type="file" class="form-control {% if realizar_ofrecimiento_form.imagen.errors %}is-invalid{% endif %}" placeholder="imagen" name="imagen" accept="image/*" value="{{ request.POST.imagen }}">
                    {% for error in realizar_ofrecimiento_form.imagen.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                </div>
                <div class="mb-3">
                    <label class="form-label" style="font-size: 20px;">Categoría</label>
                    <select name="categoriaId" class="form-control">
                        {% for categoria in realizar_ofrecimiento_form.fields.categoriaId.queryset %}
                            <option value="{{ categoria.pk }}">{{ categoria.titulo }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label" style="font-size: 20px;">Sucursal</label>
                    <select name="sucursalId" class="form-control">
                        {% for sucursal in realizar_ofrecimiento_form.fields.sucursalId.queryset %}
                            <option value="{{ sucursal.pk }}">{{ sucursal.nombre }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" value="guardar" class="btn btn-primary">Ofrecer</button>
            </div>
        </div>
    </form>

{% if realizar_ofrecimiento_form.errors %}
    <div class="errors">
        <p>Hubo algunos errores en el formulario:</p>
        <ul>
            {% for field in realizar_ofrecimiento_form %}
                {% for error in errors %}
                    <li>{{ field }}: {{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    </div>
{% endif %}

{% endblock %}

proyectoCaritas/HopeTrade/templates/ofrecimientos/rechazar_ofrecimiento.html
{% extends 'base.html' %}

{% block title %}
        <title>Rechazar Ofrecimiento</title>
{% endblock title %}

{% block content %}
        
<form method="POST">
        <div class="container mt-5">
                <div class="row justify-content-center">
                        <div class="col-md-6 text-center">
                                {% csrf_token %}
                                <div class="card">
                                        <div class="card-body">
                                                <h2>Escribe la razón por la que deseas rechazar el ofrecimiento:</h2>
                                                {{ form.as_p }}

                                                <button type="submit" class="btn btn-success">
                                                        Enviar
                                                </button>
                                                
                                                <a href="{% url 'ofrecimientos:cancelar_operacion' publicacionId %}" class="btn btn-danger">Cancelar</a>
                                        </div>
                                </div>
                        </div>
                </div>
        </div>
</form>

{% endblock content %}

proyectoCaritas/HopeTrade/templates/ofrecimientos/ver_ofrecimientos.html
{% extends 'base.html' %}
{% block title %}
        <title>Ofrecimientos de la Publicacion</title>
{% endblock title %}

{% block content %}
<form method="GET">
    {% csrf_token %}
    {% for msg in messages %}
        {% if msg.level == 25 %}
          <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
            <symbol id="check-circle-fill" viewBox="0 0 16 16">
              <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"></path>
            </symbol>
          </svg>
          <div class="alert alert-success d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"></use></svg>
              <div>
                {{ msg }}
              </div>
            <button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% elif msg.level == 30 %}
          <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
            <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
              <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </symbol>
          </svg>
            
          <div class="alert alert-warning d-flex align-items-center" role="alert">
              <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
              <div>
                {{ msg }}
              </div>
              <button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endif %}
      {% endfor%}
        {% if ofrecimientosPublicacion %}
        <main class="container  mt-5">
            <div class="row">
            {% for ofrecimiento in ofrecimientosPublicacion %}
                <div class="col-md-3 mb-4 d-flex align-items-stretch">
                    <div class="card shadow-sm w-100">
                        <div class="card-body d-flex flex-column">
                            <h5 class="card-title mb-3">{{ ofrecimiento.articulo }}</h5>
                            <h6 class="card-subtitle mb-3 text-muted">{{ ofrecimiento.descripcion }}</h6>
                            <h7 class="card-subtitle mb-3 text-muted">Cantidad: {{ ofrecimiento.cantidad }}</h7>
                            <h7 class="card-subtitle mb-3 text-muted">Fecha: {{ ofrecimiento.fecha }}</h7>
                            <h7 class="card-subtitle mb-3 text-muted">Sucursal: {{ ofrecimiento.sucursalId.nombre }}</h7>
                            <h7 class="card-subtitle mb-3 text-muted">Ubicacion: {{ ofrecimiento.sucursalId.ubicacion }}</h7>
                            <h6 class="card-subtitle mb-3 text-muted">Realizado por:
                              <a class="text-center" href="{% url 'sesiones:view_profile_user' ofrecimiento.usuarioId.id %}">
                                  {{ ofrecimiento.usuarioId.personaId.nombre }} {{ofrecimiento.usuarioId.personaId.apellido}}
                              </a>
                          </h6>
                            <img src="data:image/png;base64,{{ ofrecimiento.imagen }}"
                                class="img-fluid m-3 shadow-sm ratio-1x1 "
                                style="border: 1px solid #ddd"
                                alt="Imagen">
                            <div class="d-flex justify-content-center">
                                <a href="{% url 'ofrecimientos:aceptar_ofrecimiento' ofrecimiento.id %}" class="btn btn-success m-1">Aceptar</a>
                                <a href="{% url 'ofrecimientos:rechazar_ofrecimiento' ofrecimiento.id %}" class="btn btn-danger m-1">Rechazar</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </main>
        {% endif %}

</form>
{% endblock %}