proyectoCaritas/HopeTrade/hopetrade/urls.py
from django.contrib import admin
from django.urls import path, include
from sesiones import views as sesiones

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sesiones/', include(('sesiones.urls', 'sesiones'))),
    path('publicaciones/', include(('publicaciones.urls', 'publicaciones'))),
    path('intercambios/', include(('intercambios.urls', 'intercambios'))),
    path('listados/', include(('listados.urls', 'listados'))),
    path('', sesiones.ver_landing_page),
    path('ofrecimientos/', include('ofrecimientos.urls')),
    path('historiales/', include(('historiales.urls', 'historiales'))),
    path('estadisticas/', include(('estadisticas.urls', 'estadisticas'))),
    path('donaciones/', include(('donaciones.urls', 'donaciones')))
]

proyectoCaritas/HopeTrade/listados/urls.py
from django.urls import path
from . import views
from intercambios import views as intercambios_views

urlpatterns = [
    path('agregar_categoria/', views.agregar_categoria, name='agregar_categoria'),
    path('listar_categorias/', views.listar_categorias, name='listar_categorias'),
    path('editar_categoria/<int:categoria_id>/', views.editar_categoria, name='editar_categoria'),
    path('eliminar_categoria/<int:categoria_id>/', views.eliminar_categoria, name='eliminar_categoria'),
    path('listar_intercambios_del_dia/', views.list_exchanges_today, name='listar_intercambios_del_dia'),
    path('listar_intercambios_del_dia/confirmar/<int:intercambio_id>/', intercambios_views.confirm_exchange, name='listar_intercambios_del_dia_confirmar'),
]

proyectoCaritas/HopeTrade/ofrecimientos/urls.py
from django.urls import path
from . import views

app_name = 'ofrecimientos'

urlpatterns = [
    path('publicaciones/realizar_ofrecimiento/', views.realizar_ofrecimiento),
    path('seleccionar_publicacion/<int:publicacion_id>/realizar_ofrecimiento/', views.realizar_ofrecimiento, name='realizar_ofrecimiento'),
    path('ver_ofrecimientos/<int:publicacion_id>', views.ver_ofrecimientos, name='ver_ofrecimientos'),
    path('aceptar_ofrecimiento/<int:ofrecimiento_id>', views.aceptar_ofrecimiento, name='aceptar_ofrecimiento'),
    path('rechazar_ofrecimiento/<int:ofrecimiento_id>', views.rechazar_ofrecimiento, name='rechazar_ofrecimiento'),
    path('ver_mis_ofrecimientos/<int:user_id>', views.ver_mis_ofrecimientos, name='ver_mis_ofrecimientos'),
    path('eliminar_ofrecimientos/<int:ofrecimiento_id>', views.eliminar_ofrecimiento, name='eliminar_ofrecimiento'),
    path('cancelar_operacion/<int:publicacion_id>', views.cancelar_operacion, name='cancelar_operacion'),

]

proyectoCaritas/HopeTrade/publicaciones/urls.py
from django.urls import path
from publicaciones import views as publicaciones

urlpatterns = [
    path('realizar_publicacion/', publicaciones.realizar_publicacion, name='realizar_publicacion'),
    path('eliminar_publicacion/<int:publicacion_id>', publicaciones.eliminar_publicacion, name='eliminar_publicacion'),
    path('listar_publicaciones_sistema/', publicaciones.listar_publicaciones_sistema, name='listar_publicaciones_sistema'),
    path('listar_publicaciones_usuario/<int:user_id>', publicaciones.listar_publicaciones_usuario, name='listar_publicaciones_usuario'),
    path('realizar_comentario/', publicaciones.realizar_comentario),
    path('cancelar/', publicaciones.cancelar_operacion, name='cancelar_operacion'),
    path('seleccionar_publicacion/<int:publicacion_id>/', publicaciones.seleccionar_publicacion, name='seleccionar_publicacion'),
    path('seleccionar_publicacion/<int:publicacion_id>/realizar_comentario/', publicaciones.realizar_comentario, name='realizar_comentario'),
    path('filtrar_publicaciones_sistema/', publicaciones.filtrar_publicaciones_sistema, name='filtrar_publicaciones_sistema'),
    path('filtrar_publicaciones_usuario/', publicaciones.filtrar_publicaciones_usuario, name='filtrar_publicaciones_usuario'),
    path('listar_publicaciones_favoritas/', publicaciones.listar_publicaciones_favoritas, name='listar_publicaciones_favoritas'),
    path('agregar_publicacion_favorita/<int:publicacion_id>/', publicaciones.agregar_publicacion_favorita, name='agregar_publicacion_favorita'),
    path('eliminar_publicacion_favorita/<int:publicacionfav_id>/<int:publicacion_id>/', publicaciones.eliminar_publicacion_favorita, name='eliminar_publicacion_favorita'),
]



proyectoCaritas/HopeTrade/publicaciones/models.py
from django.db import models
from sesiones.models import Usuario
from listados.models import Categoria

# Create your models here.
class Publicacion(models.Model):
    titulo = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=250)
    cantidad = models.IntegerField()
    imagen = models.BinaryField(null=True, blank=True, editable=True)
    estado = models.TextField()
    usuarioId = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    categoriaId = models.ForeignKey(Categoria,  on_delete=models.CASCADE)

class Comentario(models.Model):
    texto = models.CharField(max_length=100)
    fecha = models.DateTimeField()
    usuarioId = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    publicacionId = models.ForeignKey(Publicacion, on_delete=models.CASCADE)
    comentarioId = models.ForeignKey("self", blank=True, null=True, on_delete=models.CASCADE)

class PublicacionFavorita(models.Model):
    usuarioId = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    publicacionId = models.ForeignKey(Publicacion, on_delete=models.CASCADE)

proyectoCaritas/HopeTrade/publicaciones/forms.py
from django import forms
from listados.models import Categoria
from .models import Publicacion
from .models import Comentario

class RealizarPublicacion(forms.ModelForm):
    categoriaId = forms.ModelChoiceField(queryset=Categoria.objects.all(), 
    widget=forms.Select(attrs={'class': 'form-control'}))
    class Meta:
        model = Publicacion
        fields = ['titulo','descripcion','cantidad','imagen','categoriaId']
    imagen = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super(RealizarPublicacion, self).__init__(*args, **kwargs)
        # Personalizamos el widget para que muestre el titulo de la categoría
        self.fields['categoriaId'].label_from_instance = lambda obj: "%s" % obj.titulo

class RealizarComentario(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['texto',]

proyectoCaritas/HopeTrade/publicaciones/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from publicaciones.models import Publicacion
from publicaciones.models import Comentario
from publicaciones.models import PublicacionFavorita
from ofrecimientos.models import Ofrecimiento
from listados.models import Categoria
from sesiones.models import Usuario
from .forms import RealizarPublicacion
from .forms import RealizarComentario
from datetime import datetime
from historiales.models import Historial, PublicacionHistorial
import base64

# Create your views here.
def realizar_publicacion(request):
    if request.method == "POST":    
        realizar_publicacion_form = RealizarPublicacion(request.POST, request.FILES)
        if realizar_publicacion_form.is_valid():
            try:
                publicacion = realizar_publicacion_form.save(commit=False)
                usuarioId = request.session.get('rol_id')
                publicacion.usuarioId = Usuario.objects.get(id=usuarioId) #hay que modificar el user
                if Publicacion.objects.filter(titulo=publicacion.titulo, usuarioId=publicacion.usuarioId).exclude(estado="eliminada").exclude(estado="finalizada").exists():
                    return render(request, "publicaciones/realizar_publicacion.html", {
                    'form': RealizarPublicacion(),
                    "error": 'No se pudo realizar la publicación, actualmente ya posee una publicación con el mismo título'
                })  
                publicacion.categoria_id = realizar_publicacion_form.cleaned_data['categoriaId'].id
                publicacion.estado = "disponible"
                imagen=(
                    base64.b64encode(realizar_publicacion_form.cleaned_data["imagen"].read())
                    if realizar_publicacion_form.cleaned_data["imagen"]
                    else realizar_publicacion_form.cleaned_data["imagen"]
                )
                publicacion.imagen = imagen
                publicacion.save()
                messages.success(request, "Su publicacion se creó exitosamente")
                ruta = "/publicaciones/listar_publicaciones_usuario/" + str(request.session['rol_id'])
                #SE CREA UN LOG EN EL HISTORIAL
                historial = Historial.objects.create(estado="disponible", fecha=datetime.now())
                PublicacionHistorial.objects.create(publicacionId=publicacion, historialId=historial)
                return redirect(ruta)
            except:
                return render(request, "publicaciones/realizar_publicacion.html", {
                    'form': RealizarPublicacion(),
                    "error": 'algo salió mal'
                })  
    else:
        realizar_publicacion_form = RealizarPublicacion()
    return render(request, "publicaciones/realizar_publicacion.html", {
        'form': RealizarPublicacion()
    })

def cancelar_operacion(request):
    return redirect('publicaciones:listar_publicaciones_sistema')

def realizar_comentario(request, publicacion_id):
    if request.method == "POST":
        realizar_comentario_form = RealizarComentario(request.POST)
        if realizar_comentario_form.is_valid():
            try:
                comentario = realizar_comentario_form.save(commit=False)
                comentario.fecha = datetime.now()
                usuarioId = request.session.get('rol_id')
                comentario.usuarioId = Usuario.objects.get(id=usuarioId)
                comentario.publicacionId = Publicacion.objects.get(id=publicacion_id) 
                comentario.save()
                ruta = "/publicaciones/seleccionar_publicacion/" + str(publicacion_id)
                return redirect(ruta)
            except:
                return render(request, "publicaciones/realizar_comentario.html", {
                    'form': RealizarComentario(),
                    "error": 'algo salió mal'
                })
    return render(request, "publicaciones/realizar_comentario.html", {
        'form': RealizarComentario()
    })

def listar_publicaciones_sistema(request):
    publicacionesSistema = Publicacion.objects.all()
    if request.session['rol'] != 'administrador':
        publicacionesSistema = Publicacion.objects.all().exclude(estado='eliminada').exclude(estado='aceptada').exclude(estado="finalizada")
    categorias = Categoria.objects.all()
    categorias_eliminadas = Categoria.objects.filter(estado='eliminada')
    for cat in categorias_eliminadas:
        if not publicacionesSistema.filter(categoriaId=cat).exists():
            categorias.exclude(id=cat.id)
    if len(publicacionesSistema) == 0:
        messages.warning(request, 'No existen publicaciones en el sistema')
    return render(request, "publicaciones/listar_publicaciones_sistema.html", {
        'publicacionesSistema': publicacionesSistema,
        'categorias': categorias,
    })


def listar_publicaciones_usuario(request, user_id):
    usuario = Usuario.objects.get(id=user_id)
    publicacionesUsuario = Publicacion.objects.filter(usuarioId=usuario).exclude(estado='eliminada').exclude(estado='aceptada').exclude(estado="finalizada")
    categorias = Categoria.objects.all()
    categorias_eliminadas = Categoria.objects.filter(estado='eliminada')
    for cat in categorias_eliminadas:
        if not publicacionesUsuario.filter(categoriaId=cat).exists():
            categorias.exclude(id=cat.id)
    if len(publicacionesUsuario) == 0:
        messages.warning(request, 'No existen publicaciones del usuario')
    return render(request, "publicaciones/listar_publicaciones_usuario.html", {
        'publicacionesUsuario': publicacionesUsuario,
        'categorias': categorias,
    })  

def seleccionar_publicacion(request, publicacion_id):
    publicacion = Publicacion.objects.get(id=publicacion_id)
    comentarios = Comentario.objects.filter(publicacionId=publicacion_id)
    usuario_id = request.session['rol_id']
    is_favorita = False
    publicacion_favorita_id = None
    if usuario_id:
        favorita = PublicacionFavorita.objects.filter(usuarioId_id=usuario_id, publicacionId_id=publicacion_id).first()
        if favorita:
            is_favorita = True
            publicacion_favorita_id = favorita.id
    if bool(publicacion.imagen):
        publicacion_imagen = publicacion.imagen.decode("utf-8")
    else:
        publicacion_imagen = None
    return render(request, 'publicaciones/seleccionar_publicacion.html', {'publicacion': publicacion, 'comentarios': comentarios, 'publicacion_imagen': publicacion_imagen, 'is_favorita': is_favorita,
        'publicacion_favorita_id': publicacion_favorita_id,})

def eliminar_publicacion(request, publicacion_id):
    publicacion = Publicacion.objects.get(id=publicacion_id)
    if request.method == "POST":
        ofrecimientos = Ofrecimiento.objects.filter(publicacionId=publicacion_id).exclude(estado='eliminado')
        if not ofrecimientos:
            publicacion.estado = 'eliminada'
            publicacion.save()
            #SE CREA UN LOG EN EL HISTORIAL DE PUBLICACIONES
            historial = Historial.objects.create(estado="eliminada", fecha=datetime.now())
            PublicacionHistorial.objects.create(publicacionId=publicacion, historialId=historial)
            messages.success(request, "La publicación se eliminó exitosamente")
        else:
            messages.warning(request, "No se puede eliminar una publicación con ofrecimientos pendientes")
        if request.session['rol'] == 'usuario':
            ruta = "/publicaciones/listar_publicaciones_usuario/" + str(request.session['rol_id'])
        else:
            ruta = "/publicaciones/listar_publicaciones_sistema"
        return redirect(ruta)
    return render(request, 'publicaciones/eliminar_publicacion.html', { 'publicacion': publicacion })

def filtrar_publicaciones_sistema(request):
    publicaciones = Publicacion.objects.all()
    if request.session['rol'] != 'administrador':
        publicaciones = Publicacion.objects.all().exclude(estado='eliminada').exclude(estado='aceptada').exclude(estado="finalizada")
    categorias = Categoria.objects.all()
    categorias_eliminadas = Categoria.objects.filter(estado='eliminada')
    for cat in categorias_eliminadas:
        if not publicaciones.filter(categoriaId=cat).exists():
            categorias.exclude(id=cat.id)
    categoria = request.POST.get('categoria')
    reputacion = request.POST.get('reputacion')
    estado = request.POST.get('estado')
    categoria_seleccionada = None
    estado_seleccionado = None
    reputacion_seleccionada=None
    if categoria != 'Categoria':
        if categoria.isdigit():
            publicaciones = publicaciones.filter(categoriaId__id=categoria)
            categoria_seleccionada = Categoria.objects.get(id=categoria)
        else:
            categoria_seleccionada = Categoria.objects.get(titulo=categoria)
            publicaciones = publicaciones.filter(categoriaId__id=categoria_seleccionada.id)
    if reputacion is not None and reputacion != 'Reputacion':
        reputacion_int = int(reputacion)
        #traigo las publicaciones con reputacion >= a lo que pide el filtro y < lo que pide el filtro +1
        publicaciones = publicaciones.filter(usuarioId__reputacion__gte=reputacion_int, usuarioId__reputacion__lt=reputacion_int + 1)
        reputacion_seleccionada = reputacion
    if estado != 'Estado' and estado != None:
        publicaciones = publicaciones.filter(estado=estado)
        estado_seleccionado = estado
    if len(publicaciones) == 0:
        messages.warning(request, f'No existen publicaciones para el filtro seleccionado')
    return render(request, "publicaciones/listar_publicaciones_sistema.html", {
        'publicacionesSistema': publicaciones,
        'categorias': categorias,
        'categoria_seleccionada':categoria_seleccionada,

proyectoCaritas/HopeTrade/templates/publicaciones/eliminar_publicacion.html
{% extends 'base.html' %}

{% block title %}
        <title>Eliminar Publicacion</title>
{% endblock title %}

{% block content %}

<form method="POST">

        {% csrf_token %}
    
        <h2>¿Seguro que desea eliminar la publicacion {{ publicacion.titulo }}?</h2>
        <form method="POST">
            <button type="submit" class="btn btn-danger">
                Aceptar
            </button>
        </form>
        {% if request.session.rol == "usuario" %}
            <form action="{% url 'publicaciones:listar_publicaciones_usuario' request.session.rol_id %}" method="GET">
                <button type="submit" class="btn btn-secondary">
                        Cancelar
                </button>
            </form>
        {% else %}
            <form action="{% url 'publicaciones:listar_publicaciones_sistema' %}" method="GET">
                <button type="submit" class="btn btn-secondary">
                    Cancelar
                </button>
            </form>
        {% endif %}
</form>
{% endblock content %}

proyectoCaritas/HopeTrade/templates/publicaciones/listar_publicaciones_favoritas.html
{% extends 'base.html' %}

{% block title %}
    <title>Publicaciones favoritas</title>
{% endblock title %}
{% block content %}
<br>
{% for msg in messages %}
    {% if msg.level == 25 %}
        <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
            <symbol id="check-circle-fill" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"></path>
            </symbol>
        </svg>
        <div class="alert alert-success d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Success:">
                <use xlink:href="#check-circle-fill"></use>
            </svg>
            <div>
                {{ msg }}
            </div>
            <button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% elif msg.level == 30 %}
        <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
            <symbol id="exclamation-triangle-fill" viewBox="0 0 16 16">
                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </symbol>
        </svg>
        <div class="alert alert-warning d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Warning:">
                <use xlink:href="#exclamation-triangle-fill"/>
            </svg>
            <div>
                {{ msg }}
            </div>
            <button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}
{% endfor %}
{% csrf_token %}
{% if listado_favoritas %}
    <div class="container">
        <div class="row">
            {% for favorita in listado_favoritas %}
                <div class="col-md-3 mb-4 d-flex align-items-stretch">
                    <div class="card shadow-sm" style="width: 100%;">
                        <div class="card-body">
                            <h5 class="card-title mb-3">{{ favorita.publicacionId.titulo }}</h5>
                            <h6 class="card-subtitle mb-3 text-body-secondary">Categoria: {{ favorita.publicacionId.categoriaId.titulo }}</h6>
                            <h6 class="card-subtitle mb-3 text-body-secondary">Descripcion: {{ favorita.publicacionId.descripcion }}</h6>
                            <a href="{% url 'publicaciones:seleccionar_publicacion' favorita.publicacionId.id %}" class="btn btn-primary">Ver</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endif %}
{% endblock %}

proyectoCaritas/HopeTrade/templates/publicaciones/realizar_comentario.html
{% extends 'base.html' %}

{% block title %}
        <title>Comentario</title>
{% endblock title %}
{% block content %}
    <h1>Nuevo Comentario<h1>
    <form method="POST">
    
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" value="guardar" class="btn btn-primary">Comentar</button>
    
    </form>
{% endblock %}

proyectoCaritas/HopeTrade/templates/publicaciones/realizar_publicacion.html
{% extends 'base.html' %}

{% block title %}
        <title>Realizar Publicacion</title>
{% endblock title %}
{% block content %}
<h1>Nueva Publicacion<h1></h1>

<form method="POST" enctype="multipart/form-data">

    {% csrf_token %}
    {{ form.as_p }}
    
    <button type="submit" value="guardar" class="btn btn-success">Realizar Publicacion</button>
    <a href="{% url 'publicaciones:cancelar_operacion' %}" class="btn btn-primary">Cancelar</a>

</form>
{% endblock %}

proyectoCaritas/HopeTrade/templates/publicaciones/seleccionar_publicacion.html
{% extends 'base.html' %}

{% block title %}
    <title>Seleccionar Publicacion</title>
{% endblock title %}
{% block content %}
{% for msg in messages %}
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="check-circle-fill" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"></path>
        </symbol>
    </svg>

    <div class="alert alert-success d-flex align-items-center" role="alert">
        <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"></use></svg>
        <div>
            {{ msg }}
        </div>
        <button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}
    <main class="container">
        <div class="row">
            <div class="col-md-3 mb-4">
                <div class="card" style="width: 20rem; position: relative;">
                    <div class="card-body">
                        {% if request.session.rol == 'usuario' %}
                            {% if is_favorita %}
                                <a href="{% url 'publicaciones:eliminar_publicacion_favorita' publicacion_favorita_id publicacion.id %}" class="favorite-icon" style="position: absolute; top: 10px; right: 10px;">
                                    <i class="fas fa-star" style="color: gold;"></i>
                                </a>
                            {% else %}
                                <a href="{% url 'publicaciones:agregar_publicacion_favorita' publicacion.id %}" class="favorite-icon" style="position: absolute; top: 10px; right: 10px;">
                                    <i class="far fa-star"></i>
                                </a>
                            {% endif %}
                        {% endif %}
                        <a href="{% url 'sesiones:view_profile_user' publicacion.usuarioId.id %}">
                            {{ publicacion.usuarioId.personaId.nombre }}
                        </a>
                        <h5 class="card-title mb-3"> {{publicacion.titulo}}</h5>
                        <h6 class="card-subtitle mb-3 text-body-secondary">Categoria: {{ publicacion.categoriaId.titulo }}</h6>
                        <h6 class="card-subtitle mb-3 text-body-secondary">{{ publicacion.descripcion }}</h6>
                        <h7 class="card-subtitle mb-3 text-body-secondary">cantidad: {{ publicacion.cantidad }}</h7>
                        <div class="col-md-8 text-center">
                            <img src="data:image/png;base64,{{ publicacion_imagen }}"
                                 class="img-fluid m-3 shadow-sm ratio-1x1 "
                                 style="border: 1px solid #ddd"
                                 alt="Imagen">
                        </div>
                        {% if request.session.rol == 'administrador'%}
                            <a href="{% url 'publicaciones:eliminar_publicacion' publicacion.id %}" class="btn btn-danger">Eliminar</a>
                        {% endif %}
                    </div>
                </div>
                {% if request.session.rol == 'usuario' %}
                    {% if request.session.usuario_id == publicacion.usuarioId.personaId.id %}
                        <div class="d-flex flex-column align-items-start">
                            <a href="{% url 'ofrecimientos:ver_ofrecimientos' publicacion.id %}" class="btn mb-2" style="background-color: #8f33ff; color: white; border-color: #500ce1;">Ver ofrecimientos</a>
                        </div>
                    {% else %}
                        {% if publicacion.estado == 'disponible' %}
                            <div class="d-flex flex-column align-items-start">
                                <a href="{% url 'ofrecimientos:realizar_ofrecimiento' publicacion.id %}" class="btn mb-2" style="background-color: #8f33ff; color: white; border-color: #500ce1;">Realizar ofrecimiento</a>
                            </div>
                        {% endif %}
                    {% endif %}
                {% endif %}
                <h3>Comentarios:</h3>
                <ul>
                    {% for comentario in comentarios %}
                        <li>
                            <a href="{% url 'sesiones:view_profile_user' comentario.usuarioId.id %}">
                                {{ comentario.usuarioId.personaId.nombre }}:
                            </a>
                            {{ comentario.texto }}, {{ comentario.fecha }}
                        </li>
                    {% endfor %}
                    {% if request.session.rol == 'usuario' %}
                        <div class="d-flex flex-column align-items-start">
                            <a href="{% url 'publicaciones:realizar_comentario' publicacion.id %}" class="btn btn-primary mb-2">Realizar comentario</a>
                        </div>
                    {% endif %}
                </ul>
            </div>
        </div>
    </main>
{% endblock %}